config/routes.rb
DropzoneRails::Application.routes.draw do

  match 'upload' => "home#upload", as: :upload
  match '/:asset_id/set_primary' => "home#set_primary", as: :set_primary
  match '/:asset_id/remove_image' => "home#remove_image", as: :remove_image

  root :to => 'home#index'

end

app/models/asset.rb
class Asset
  include Mongoid::Document

  mount_uploader :image, AssetUploader

  field :file_name  
  field :file_size
  field :is_primary, type: Boolean, default: false

  scope :primary, where(is_primary: true)

  def name
    self.file_name
  end

  def size
    self.file_size
  end

  def remote_url 
    self.image.url
  end
  
  def type
    "image/png"
  end

  def as_json(options= {})
    options.merge!(only: [:_id, :is_primary], methods: [:name, :size, :remote_url, :type])
    super
  end

  private

  def update_asset_attributes
    if image.present? && image_changed?
      self.file_size = image.file.size
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :protect_from_forgery, only: :upload

  def index
    @assets = Asset.all    
  end

  def upload
    asset = Asset.new(image: params[:image], file_name: params[:image].original_filename)
    asset.save!
    render json: {asset_id: asset.id} 
  end

  def remove_image
    Asset.find(params[:asset_id]).destroy
    render nothing: true
  end

  def set_primary
    Asset.primary.update_all(is_primary: false)

    asset = Asset.find(params[:asset_id])
    asset.update_attributes(is_primary: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.span12
  #images
    #my-zone
      %h3 My Images
      %form{action: upload_path, class: "dropzone#{' dz-started' if @assets.count > 0}", id: 'assets-dropzone'}

:coffeescript
  @images = #{@assets.to_json}

app/views/home/set_primary.js.haml
$('#assets-dropzone').find('.dz-primary').removeClass('dz-primary')
$('#'+"#{params[:asset_id]}").addClass('dz-primary')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DropzoneRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>